<a href="https://colab.research.google.com/github/yektaKamane/Linear-Algebra-Project/blob/main/Linear_Algebra_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [ ]:
import numpy as np
import pandas as pd

# Import dataset

In [96]:
dataset = pd.read_csv('cars.csv')
dataset = dataset.dropna()

In [97]:
dataset.head()

_id  acceleration body_color  body_status  \
0  62c020245ac6166d04f27483           9.7       سفید  گلگیر تعویض   
1  62c020245ac6166d04f27484          11.1       سفید   یک لکه رنگ   
2  62c020245ac6166d04f27485           9.2       سفید     بدون رنگ   
3  62c020245ac6166d04f27486          11.6  سفید صدفی   یک لکه رنگ   
4  62c020245ac6166d04f27487          11.3  نوک مدادی  گلگیر تعویض   

       body_type    brand                       engine  fuel_consumption  \
0  passenger_car       mg          4 سیلندر توربوشارژ                6.9   
1      crossover      kia                4 سیلندر GDI                8.8   
2      crossover    lexus  4 سیلندر با موتور الکتریکی                5.1   
3           None  peugeot                4 سیلندر TU5                6.6   
4           None      kia                    4 سیلندر                7.0   

  fuel_type inside_color   mileage     model       price  \
0    بنزینی         مشکی   98000.0       360   450000000   
1    بنزینی         مشکی  111000.0   sorento  2050000000   
2   هیبریدی    سفید صدفی   18000.0  nxhybrid  4300000000   
3    بنزینی         مشکی   70000.0       207   350000000   
4    بنزینی         طوسی  230000.0     rioir   189000000   

                                                 url  volume  year  
0  https://bama.ir/car/detail-yef9zxzr-mg-360-att...     1.5  2018  
1  https://bama.ir/car/detail-ob1tf9i3-kia-sorent...     2.4  2015  
2  https://bama.ir/car/detail-2xy9brk9-lexus-nxhy...     2.5  2017  
3  https://bama.ir/car/detail-xx8wmki9-peugeot-20...     1.6  2020  
4  https://bama.ir/car/detail-dxwsqo-kia-rioir-mt...     1.5  2008

# Define X and Y

In [98]:
X = dataset.drop(['price', 'url', '_id'], axis=1)
Y = dataset['price'].values

In [99]:
X

acceleration body_color  body_status      body_type    brand  \
0               9.7       سفید  گلگیر تعویض  passenger_car       mg   
1              11.1       سفید   یک لکه رنگ      crossover      kia   
2               9.2       سفید     بدون رنگ      crossover    lexus   
3              11.6  سفید صدفی   یک لکه رنگ           None  peugeot   
4              11.3  نوک مدادی  گلگیر تعویض           None      kia   
...             ...        ...          ...            ...      ...   
18348          15.5        کرم     بدون رنگ         pickup    amico   
18349          10.5       مشکی     بدون رنگ      crossover    haima   
18350          13.0       سفید     بدون رنگ  passenger_car     tiba   
18352           6.9    نقره ای     بدون رنگ      crossover    volvo   
18353           6.4       سفید   دو لکه رنگ      crossover      bmw   

                                  engine  fuel_consumption   fuel_type  \
0                    4 سیلندر توربوشارژ                6.9      بنزینی   
1                          4 سیلندر GDI                8.8      بنزینی   
2            4 سیلندر با موتور الکتریکی                5.1     هیبریدی   
3                          4 سیلندر TU5                6.6      بنزینی   
4                              4 سیلندر                7.0      بنزینی   
...                                  ...               ...         ...   
18348        4 سیلندر دوگانه سوز (4G69)               10.7  دوگانه سوز   
18349                4 سیلندر توربوشارژ                9.7      بنزینی   
18350                      4 سیلندر M15                6.9      بنزینی   
18352  4 سیلندر توربوشارژ و سوپرشارژ T6                7.7      بنزینی   
18353       4 سیلندر توربوشارژ (N20B20)                7.4      بنزینی   

      inside_color   mileage      model  volume  year  
0             مشکی   98000.0        360     1.5  2018  
1             مشکی  111000.0    sorento     2.4  2015  
2        سفید صدفی   18000.0   nxhybrid     2.5  2017  
3             مشکی   70000.0        207     1.6  2020  
4             طوسی  230000.0      rioir     1.5  2008  
...            ...       ...        ...     ...   ...  
18348         مشکی       0.0  asna4door     2.4  2021  
18349        مارون       0.0         s7     1.8  2020  
18350      خاکستری       0.0      sedan     1.5  2020  
18352          کرم  120000.0       xc90     2.0  2016  
18353         موکا   50000.0         x4     2.0  2016  

[16672 rows x 13 columns]

In [100]:
print(Y)

[ 450000000 2050000000 4300000000 ...  185000000 3800000000 3250000000]


# Encoding non-numerical data to numeric

In [101]:
numeric_x = X.drop(['body_color', 'body_status', 'body_type', 'brand', 'engine', 'fuel_type', 'inside_color', 'model'], axis=1).values
non_numeric_x = X[['body_color', 'body_status', 'body_type', 'brand', 'engine', 'fuel_type', 'inside_color', 'model']].values

# print(numeric_x)
print(non_numeric_x)

[['سفید' 'گلگیر تعویض' 'passenger_car' ... 'بنزینی' 'مشکی' '360']
 ['سفید' 'یک لکه رنگ' 'crossover' ... 'بنزینی' 'مشکی' 'sorento']
 ['سفید' 'بدون رنگ' 'crossover' ... 'هیبریدی' 'سفید صدفی' 'nxhybrid']
 ...
 ['سفید' 'بدون رنگ' 'passenger_car' ... 'بنزینی' 'خاکستری' 'sedan']
 ['نقره ای' 'بدون رنگ' 'crossover' ... 'بنزینی' 'کرم' 'xc90']
 ['سفید' 'دو لکه رنگ' 'crossover' ... 'بنزینی' 'موکا' 'x4']]


converting to numeric

In [102]:
from inspect import EndOfBlock
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

x = np.matrix(non_numeric_x)
x_t = x.transpose()
# print(x_t)

# encoded_features = np.empty((0))
encoded_features = []
for feature in x_t:
  rowTmp = np.ravel(feature)
  le.fit(rowTmp)
  transform = le.transform(rowTmp)
  encoded_features.append(transform)

new_non_numeric_x = np.matrix(encoded_features).transpose()
print(new_non_numeric_x)



[[ 18  13   5 ...   0  16  24]
 [ 18  16   3 ...   0  16 230]
 [ 18   1   3 ...   3   9 181]
 ...
 [ 18   1   5 ...   0   2 224]
 [ 30   1   3 ...   0  21 270]
 [ 18   5   3 ...   0  17 260]]


# merging

In [103]:
merged_x = np.concatenate((numeric_x, new_non_numeric_x), axis=1)
print(merged_x)

[[9.70e+00 6.90e+00 9.80e+04 ... 0.00e+00 1.60e+01 2.40e+01]
 [1.11e+01 8.80e+00 1.11e+05 ... 0.00e+00 1.60e+01 2.30e+02]
 [9.20e+00 5.10e+00 1.80e+04 ... 3.00e+00 9.00e+00 1.81e+02]
 ...
 [1.30e+01 6.90e+00 0.00e+00 ... 0.00e+00 2.00e+00 2.24e+02]
 [6.90e+00 7.70e+00 1.20e+05 ... 0.00e+00 2.10e+01 2.70e+02]
 [6.40e+00 7.40e+00 5.00e+04 ... 0.00e+00 1.70e+01 2.60e+02]]


# normalize X 

In [105]:
normalized_x = preprocessing.normalize(merged_x, axis=0, norm='l1')
print(normalized_x)

[[5.00763018e-05 5.48458276e-05 7.48284036e-05 ... 0.00000000e+00
  6.26576231e-05 1.15460053e-05]
 [5.73038093e-05 6.99483018e-05 8.47546204e-05 ... 0.00000000e+00
  6.26576231e-05 1.10649217e-04]
 [4.74950492e-05 4.05382204e-05 1.37439925e-05 ... 3.27510917e-03
  3.52449130e-05 8.70761233e-05]
 ...
 [6.71125695e-05 5.48458276e-05 0.00000000e+00 ... 0.00000000e+00
  7.83220289e-06 1.07762716e-04]
 [3.56212869e-05 6.12047641e-05 9.16266167e-05 ... 0.00000000e+00
  8.22381303e-05 1.29892560e-04]
 [3.30400342e-05 5.88201629e-05 3.81777569e-05 ... 0.00000000e+00
  6.65737245e-05 1.25081724e-04]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,


# Split the dataset into training and test